// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHhWAhO6b_G-W4dPcMgpwYzUWPSVXoEY0',
    appId: '1:893870174085:web:18bd0c92ba9bb5ccaadeec',
    messagingSenderId: '893870174085',
    projectId: 'fx-guru-c019b',
    authDomain: 'fx-guru-c019b.firebaseapp.com',
    storageBucket: 'fx-guru-c019b.appspot.com',
    measurementId: 'G-00JKE66YT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD80aFItAxr9lPLvJOvrYXFEgUkv4tWZ38',
    appId: '1:893870174085:android:02b818b8c589418baadeec',
    messagingSenderId: '893870174085',
    projectId: 'fx-guru-c019b',
    storageBucket: 'fx-guru-c019b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNodW_KJ36G5ZvmWY9gESypjCy_tPtsTs',
    appId: '1:893870174085:ios:bbd2314487737b4baadeec',
    messagingSenderId: '893870174085',
    projectId: 'fx-guru-c019b',
    storageBucket: 'fx-guru-c019b.appspot.com',
    iosClientId: '893870174085-6k2si1d5qsoutlr1r3kuacst9ivlu0ui.apps.googleusercontent.com',
    iosBundleId: 'com.example.fxGuru',
  );
}
